image: rocker/verse:latest

pages:
  stage: deploy
  script:
    - apt-get update && apt-get install -y curl
    - curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb
    - dpkg -i quarto-linux-amd64.deb
    - quarto render --output-dir public
  artifacts:
    paths:
      - public
  only:
    - master
