project:
  type: website

website:
  title: "Guy Freeman"
  site-url: https://www.gfrm.in
  description: "A blog about data science, statistics, and more."
  navbar:
    right:
      - projects.qmd
      - about.qmd
      - icon: github
        href: https://github.com/gfrmin
      - icon: twitter
        href: https://twitter.com/gfrmin
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - cosmo
    css: styles.css
